### PR TITLE
Cachebox-37 Fix

### PR DESCRIPTION
**Pull request by eppinger**
use the logbox config from the cachebox config if in standalone moade

### CODE REVIEW

**Comment by bdw429s** [comment]
Thanks for the pull @eppinger!  @lmajano this seems pretty straightforward.  Can you review it?

**Comment by lmajano** [comment]
Thanks @eppinger Would be great to have some tests with this :)

**Comment by lmajano** [comment]
@eppinger thanks, is there a way for some tests?

**Comment by lmajano** [comment]
Thank you so much @eppinger I have added tests and merged manualy.

**Pull request closed without merging**
