### PR TITLE
slugify doesn't make nice German slugs

### PR DESCRIPTION
**Pull request by GunnarLieb**
German umlauts should be replace like this:
ä to ae
ü to ue
ö to oe
ß to ss

### CODE REVIEW

**Comment by Tropicalista** [comment]
Good point, I have same problem with accented characters in italian: à,è,ì,ò,ù that are used in a lot of european language. This are removed by slugify. Probably a better solution would be to add two more arguments to the function with allowedList and replaceList.

**Comment by Tropicalista** [comment]
We should also consider the approach of this SO ansers: http://stackoverflow.com/questions/9926507/coldfusion-convert-accented-regional-characters-to-plain-ascii and http://stackoverflow.com/questions/5806690/is-there-an-iconv-with-translit-equivalent-in-java/5807419#5807419

**Comment by Tropicalista** [comment]
A simple gist: http://trycf.com/gist/25ef1499ea85058712f7

**Comment by GunnarLieb** [comment]
The Gist you have posted doesn't do the right normalization for German. Germans would write AE for Ä and not A. I'm not sure about other languages

**Comment by Tropicalista** [comment]
Yes, I don't know much about german language. The gist I posted is more related to the one that I know, Italian. I suppose that a lot of accented chars are also in Spanish, portuguese and french. I think could be a nice addition.

**Comment by GunnarLieb** [comment]
Maybe we should split it up for each language? More lines of code but easier to maintain?

**Comment by lmajano** [comment]
I don't mind adding them in for many use-cases .

**Pull request merged**
