### PR TITLE
Full null support

### PR DESCRIPTION
**Pull request by elpete**
This ticket adds full null support brought in Lucee 5. ([COLDBOX-202](https://ortussolutions.atlassian.net/browse/COLDBOX-202))

The Travis CI build will need to be updated to test different engines.  I [wrote a blog post about this](http://dev.elpete.com/2016/05/11/multi-engine-ci-in-travis-with-commandbox-3-1-0/) and would be happy to also make that change if you would like.

There could be some lingering issues in the transition, but I wanted to get it up here so we could talk about any needed changes.

### CODE REVIEW

**Comment by elpete** [comment]
One question with Travis CI is how to specify Full Null Support for Lucee 5 (since it isn't on by default).

**Comment by elpete** [comment]
Also, even though this build passed, it might still have issues (since we aren't testing the full null support with Lucee 5 on Travis yet).

**Comment by bdw429s** [comment]
Wow, thanks! Full null support is a compiler option so it can't be placed in application.cfc.  To automate the setting you'd have to write it into the xml config file our set it by calling cfadmin from within the running context.

**Comment by sjdaniels** [comment]
Hey nice timing! We were just talking about this in #box-products 👍

**Comment by bdw429s** [comment]
Just got back from camping this weekend.  I see the Travis build has failed 3 times.  Are you still  working through things or do you need help to move forward?

**Comment by elpete** [comment]
@bdw429s At this point, I could use some help.  It looks like the last normal Lucee 5 build *should* have passed but ran in to a MockBox error (something I've seen intermittently while doing this; not sure why).  Other than that, the Lucee 5 with nulls build never finishes running.  I think it's during the CacheBox tests.  Any advice or ideas on 1) how to get them to run locally and 2) how to get them running on Travis would be awesome.

Also, feel free to critique the new build system.  I'm sure it can be streamlined a lot.

**Comment by elpete** [comment]
Lucee just deployed a patch fix that should help us out in this situation:

https://luceeserver.atlassian.net/browse/LDEV-888
https://github.com/lucee/Lucee/commit/8134cbccdeb1311682dc7043f8840db438347d3e

**Comment by bdw429s** [comment]
@lmajano What needs to happen to get this merged?

**Comment by elpete** [comment]
I see two things that need to happen:

1) We need a Travis build that runs this with full null support. I tried to get that working but couldn't quite get it. 

2) I don't believe CacheBox was 100% converted for full null support. At the time I was having trouble getting the CacheBox portion of the tests to run with full null support (timing out), so I was waiting until Travis was set up to do it. (This could have been a one-off issue since I haven't come back to it since.)

**Comment by bdw429s** [comment]
@lmajano Can you do a manual run of the tests to verify this pull until we can figure out the build bit?  This pull is from May and I'd hate to see Eric's work sit around until conflicts start appearing with the main branch.

**Comment by lmajano** [comment]
@elpete can you split this pull request in two.  

1) For null support
2) For the automated travis testing

Thanks

**Pull request closed without merging**
