### PR TITLE
Update ConsoleAppender to use TaskScheduler

### PR DESCRIPTION
**Pull request by jcberquist**
This pull request copies over the new approach making use of the TaskScheduler in the FileAppender to use in the ConsoleAppender as well.

### CODE REVIEW

**Comment by lmajano** [comment]
Thanks so much! Perfect styling!

**Comment by lmajano** [comment]
https://ortussolutions.atlassian.net/browse/LOGBOX-46

**Comment by lmajano** [comment]
Just in time for RC

**Comment by jcberquist** [comment]
> Perfect styling!

😁 

I added another pull request just to comment out one of the `out()` calls - I wasn't sure which of those you wanted active and which not, so I am trying to match the file appender. I figure this particular one is a bit much, since it would result in everything being written to stdout twice.

**Pull request merged**
