### PR TITLE
Full null support

### PR DESCRIPTION
**Pull request by elpete**
Running all the tests never completes with full null support turned on.

I don't have the tools or know-how necessary to profile / debug that.

Everything passes with full null support off, though. 👍

### CODE REVIEW

**Comment by elpete** [comment]
The tests that failed run fine locally. ¯\_(ツ)_/¯

**Comment by bdw429s** [comment]
That error looks like something @lmajano and I were just looking at the other day.  I think Luis fixed it in this commit:
https://github.com/ColdBox/coldbox-platform/commit/116f1f04986b6253d26a9d6cd88ef5c95e9639c8
Have you re-based your branch from `development` recently?

**Comment by elpete** [comment]
Just today.  This branch is completely up to date.

**Comment by elpete** [comment]
Can someone re-run this build?  It looks like it failed for a random reason (`can't create directory /logs`).

**Comment by bdw429s** [comment]
The tests are finally passing on this and at least one person has tested it and says it works for them.  I'm merging this now and we'll keep an eye out for any problems it may cause.

**Comment by lmajano** [comment]
I am going through it and have some observations.  This code is repeated with the same pattern, checking the struct for existence and then a null check,

```
if( structKeyExists(refLocal,"target") && ! isNull(refLocal.target) ){
```

Why couldn't we just check for nullness:

```
if( ! isNull( refLocal.target ) ){
```

Intead of doing two checks on everything.

**Comment by lmajano** [comment]
Also, the version was not bumped, so it re-build itself in staging as 4.3

**Comment by elpete** [comment]
I see no reason why we couldn't just use the check for nullness.  Seems to work in my testing.

**Comment by lmajano** [comment]
Do you mind Eric updating another pull? I am going through the other requests today

**Pull request merged**
