### PR TITLE
COLDBOX-1096

### PR DESCRIPTION
**Pull request by jclausen**
Resolves COLDBOX-1096 - SES Enabled by default through lifecycle

### CODE REVIEW

**Comment by lmajano** [comment]
@jclausen I like where this is going. However, I think we might take it a step further.  The SES enablements where from the pre 3.x days where routing was a plugin.  At this point, there really should not be a case for turn it on/off. It will always be on as the routing service is a first class citizen now.  

I say we remove all references to any type of ses enablements.

**Comment by jclausen** [comment]
@lmajano Sounds like a plan.  I am going to have to yak-shave a bunch of tests that test for non-SES URL patterns.  I will take a look at the code and update this PR.

**Comment by lmajano** [comment]
Let me know when ready @jclausen

**Comment by jclausen** [comment]
Thanks for the bump @lmajano . I will try to get all of the tests working tomorrow

**Comment by jclausen** [comment]
@lmajano: I have updated with the recommendations.

**Comment by lmajano** [comment]
Thanks @jclausen merged manually!!!

**Pull request closed without merging**
