### PR TITLE
Update Injector.cfc

### PR DESCRIPTION
**Pull request by angel-chrystian**
When injecting the renderer, it was returning **coldbox:render as the location causing access denied("java.io.FilePermission" .....\coldbox:renderer.cfc" "read")**

Stack trace

> java.security.AccessControlException:   access denied ("java.io.FilePermission"   "D:\home\situricia.mx\SubDomains\pruebas\models\coldbox:renderer.cfc"   "read") at   java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)   at java.base/java.security.AccessController.checkPermission(AccessController.java:895)   at   java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:335)   at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:674) at   java.base/java.io.File.isFile(File.java:878) at   coldfusion.runtime.CFPage.FileExists(CFPage.java:4962) at   cfInjector2ecfc2069047518$funcLOCATEINSTANCE.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\ioc\Injector.cfc:544)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:287) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3928) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3908) at   cfInjector2ecfc2069047518$funcCONTAINSINSTANCE.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\ioc\Injector.cfc:520)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:287) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:818) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:601) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:426)   at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3380) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3357) at   cfBuilder2ecfc1765914197$funcGETPROVIDERDSL.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\ioc\Builder.cfc:625)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3869) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3850) at   cfBuilder2ecfc1765914197$funcBUILDDSLDEPENDENCY.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\ioc\Builder.cfc:420)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:823) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:629) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3302) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3277) at   cfInjector2ecfc2069047518$funcPROCESSINJECTION.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\ioc\Injector.cfc:884)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:287) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3928) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3908) at   cfInjector2ecfc2069047518$funcAUTOWIRE.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\ioc\Injector.cfc:646)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:823)   at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:629) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3302) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3277) at cfNoScope2ecfc552975167$funcGETFROMSCOPE.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\ioc\scopes\NoScope.cfc:47)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:287) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:818) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:601) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:426) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3380) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3357) at   cfInjector2ecfc2069047518$funcGETINSTANCE.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\ioc\Injector.cfc:370)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:823) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:629) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3302) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3277) at   cfFrameworkSupertype2ecfc1734914813$funcGETINSTANCE.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\FrameworkSupertype.cfc:30)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3869) at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3850)   at   cfPedidos2ecfc995435262$funcINDEX.runFunction(D:\home\situricia.mx\SubDomains\pruebas\modules_app\clientes\handlers\Pedidos.cfc:72)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484)   at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3869) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3850) at   cfEventHandler2ecfc431423389$func_PRIVATEINVOKER.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\EventHandler.cfc:89)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:823) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:629) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3302) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3277) at   cfController2ecfc980219601$funcINVOKER.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\web\Controller.cfc:902)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3869) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3850) at   cfController2ecfc980219601$func_RUNEVENT.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\web\Controller.cfc:735)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3869) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3850) at   cfController2ecfc980219601$funcRUNEVENT.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\web\Controller.cfc:467)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:823) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:629) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3302) at   coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3277) at   cfBootstrap2ecfc1323512216$funcPROCESSCOLDBOXREQUEST.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\Bootstrap.cfc:251)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:287)   at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3928) at   coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3908) at   cfBootstrap2ecfc1323512216$funcONREQUESTSTART.runFunction(D:\home\situricia.mx\SubDomains\pruebas\coldbox\system\Bootstrap.cfc:467)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at   coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:287) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:818) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:601) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:426) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3380)   at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3357) at   cfApplication2ecfc1254689733$funcONREQUESTSTART.runFunction(D:\home\situricia.mx\SubDomains\pruebas\Application.cfc:101)   at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553) at   coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484) at   coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)   at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)   at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398) at   coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371) at   coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:287) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:818) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:601) at   coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:426) at   coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:115) at   coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:286)   at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:546) at   coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)   at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) at   coldfusion.filter.PathFilter.invoke(PathFilter.java:162) at   coldfusion.filter.IpFilter.invoke(IpFilter.java:45) at   coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:96) at   coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78) at   coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)   at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) at   coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60) at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)   at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) at   coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) at   coldfusion.CfmServlet.service(CfmServlet.java:226) at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:311)   at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) at   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   at java.base/java.lang.reflect.Method.invoke(Method.java:564) at   org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282) at   org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279) at   java.base/java.security.AccessController.doPrivileged(Native Method) at   java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550) at   org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314) at   org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:225)   at   org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)   at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)   at   org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)   at java.base/java.security.AccessController.doPrivileged(Native Method) at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)   at   coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:46)   at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47) at   jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) at   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   at java.base/java.lang.reflect.Method.invoke(Method.java:564) at   org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282) at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)   at java.base/java.security.AccessController.doPrivileged(Native Method) at   java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550) at   org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314) at   org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)   at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)   at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)   at   org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)   at   org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)   at java.base/java.security.AccessController.doPrivileged(Native Method) at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at   jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) at   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   at java.base/java.lang.reflect.Method.invoke(Method.java:564) at   org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282) at   org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279) at   java.base/java.security.AccessController.doPrivileged(Native Method) at   java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550) at   org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314) at   org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)   at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)   at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)   at   org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)   at   org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)   at java.base/java.security.AccessController.doPrivileged(Native Method) at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)   at com.seefusion.Filter.doFilter(Filter.java:49) at   com.seefusion.SeeFusion.doFilter(SeeFusion.java:1500) at   jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) at   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   at java.base/java.lang.reflect.Method.invoke(Method.java:564) at   org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282) at   org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279) at   java.base/java.security.AccessController.doPrivileged(Native Method) at   java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550) at   org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314) at   org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)   at   org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)   at   org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)   at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)   at java.base/java.security.AccessController.doPrivileged(Native Method) at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)   at   org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)   at   org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:491)   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)   at   org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)   at   org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)   at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:422) at   org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)   at   org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)   at   org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)   at   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)   at   org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)   at java.base/java.lang.Thread.run(Thread.java:844)
--

### CODE REVIEW

**Comment by bdw429s** [comment]
What was the name of the CFC throwing the error?  Did it have a colon in the name?

**Comment by lmajano** [comment]
Not sure this solves the issue. I am wondering how you where trying to inject it

**Comment by angel-chrystian** [comment]
I did not inject specifically the renderer, I just pushed my application to the hosting server and I got the error shown, I wrote to support in Hostek and they said this

> D:\home\situricia.mx\SubDomains\pruebas\models\coldbox:renderer.cfc

Notice that this file has a colon ":" instead of a slash "\". We do not believe that Java is recognizing this as a valid path and therefore you are getting a permissions error on this path. We recommend that you rename this to use a slash instead of a colon.

Note: We confirmed that the sandbox permissions are set correctly and even added manual permissions that would allow this to work, but since it's not a valid path it is returning this error.

Then I added the line included in this pull request and I stopped getting the error.

**Comment by lmajano** [comment]
The colon is used as the injection DSL that wirebox interpreta and discovers the object to load. Doing this conversion actually does nothing because coldbox/renderer does not even exist. So I am not sure what is going on still. 

I still think the issue is somewhere else of why the dsl was not translated.

**Comment by angel-chrystian** [comment]
I added screen shots of the error I was getting. [https://1drv.ms/f/s!ApA82V4u9iiPh8hEI08ddm7msTBUAg](url)
This error did not show locally with commandbox, It started when I pushed to the server.

**Comment by bdw429s** [comment]
I see what's going on here.  WireBox is just testing the provider string on the off chance it happens to be a CFC path on disk.  It's probably not in 99% of the cases, but it's part of the checks we run.  Normally, the fileExists() just comes back with false, but sandbox security is just throwing an error for some reason.  Probably because colons are not valid characters in a file path so far as I know. Replacing the colon with a slash will make the path valid, but the actual fileExists check itself is fairly pointless.  I would be tempted to have tie code just return false and skip the file system checks entirely if a string comes in with a colon in it since we basically know its not a file path.

**Comment by lmajano** [comment]
That makes sense.

**Comment by bdw429s** [comment]
@lmajano What are your thoughts on the current fix provided?  @jclausen has pointed out in another thread that the Unix file system allows for colons as a valid character in file paths so this fix may not work.

**Comment by lmajano** [comment]
Wil start revisinng

**Comment by lmajano** [comment]
I agree, colons are not valid filenames.  So why not just return empty at the beginning. No need to go over all the checks.

**Comment by lmajano** [comment]
Guys, I merged the change manually, as I moved it around.  I also added a ticket for it
WIREBOX-83

**Comment by lmajano** [comment]
Thanks so much @angel-chrystian for your hard work on this one

**Comment by bdw429s** [comment]
> I agree, colons are not valid filenames

@lmajano Can you clarify who you were agreeing with?  In my previous comment I was pointing out information from @jclausen that says colons ARE valid in file paths.

**Comment by angel-chrystian** [comment]
@lmajano I'm glad to be helpful.

**Pull request closed without merging**
