### PR TITLE
Fix constructor injection with virtual inheritance

### PR DESCRIPTION
**Pull request by elpete**
Constructor injection with virtual inheritance doesn't work correctly if the target component does not have a constructor.  The virtual inheritance constructor is injected to the target, but none of the arguments are passed when calling the constructor.  This fixes that problem by adding the constructor arguments of the virtual inheritance mapping to the target mapping.

### CODE REVIEW

**Comment by lmajano** [comment]
I need some tests for this @elpete

**Comment by lmajano** [comment]
Do we have a ticket for this?

**Comment by elpete** [comment]
I modified the existing tests. And no, there’s not a ticket.

**Comment by lmajano** [comment]
I don't see any tests committed though?

**Comment by elpete** [comment]
I’m speaking of keeping the existing virtual inheritance tests passing.

**Pull request merged**
