### PR TITLE
Fix 597

### PR DESCRIPTION
**Pull request by Tropicalista**
Add an extension check to prevent that css path containing .js string is added as js

Ex https://cdnjs.cloudflare.com/ajax/libs/gridstack.js/0.3.0/gridstack-extra.min.css

### CODE REVIEW

**Comment by bdw429s** [comment]
Hi @Tropicalista , did you test this latest version?  I don't see how it would work.  If you didn't pass the fileExt parameter, `isJS` would default to false (or if you explicitly passed `css` the same would be true), but the later if statement would still treat it as JS anyway because the string `.js` still appears in the string and `findNoCase(".js", thisAsset)`  will evaluate as true.  

I would expect that if there is a passed file type, it completely overrides any "guessing".  

And finally, are you going to do the change to correct check the end of the URL for an extension.  Something along the lines of:
```js
listLast( listFirst( listFirst( thisAsset, '##' ), '?' ), '.' )
```
Here's a cleaner but more verbose one that uses some Java libs for URL parsing.
```java
var theURL = createObject( 'java', 'java.net.URL' ).init( thisAsset );
var fileUtils = createObject( 'java', 'org.apache.commons.io.FilenameUtils' );
fileUtils.getExtension( theURL.getPath() );
```

**Comment by lmajano** [comment]
So I see two pull requests with the same ticket? Which one is the one to use?

**Comment by Tropicalista** [comment]
No one is completed, I'd try to make a pull request following brad's suggestions.

**Comment by lmajano** [comment]
Should I close this, or we revamping this?

**Comment by Tropicalista** [comment]
Please close this. I will send another pr.

**Pull request closed without merging**
