### PR TITLE
COLDBOX-748: use dummy flash scope when sessions disabled

### PR DESCRIPTION
**Pull request by DominicWatson**
This is really just a safety backstop. We sometimes disable sessions for things like BOT requests and this logic defends against odd code that might try accessing the flash scope during these requests.

### CODE REVIEW

**Comment by jclausen** [comment]
I totally support a fallback when sessions are disabled. Is there any reason we couldn't point this to the `ColdboxCacheFlash` instead, so that it can persist between requests?  There are already checks in the cache flash for whether or not sessions are enabled.

**Comment by lmajano** [comment]
Yep I think it’s best to have the cache as callback.

**Comment by lmajano** [comment]
Fallback that is

**Comment by DominicWatson** [comment]
Sounds good to me - would you like me to adjust the PR?

**Comment by jclausen** [comment]
If you could, Dom, that would be great!  Should be just changing two lines.

**Comment by lmajano** [comment]
Actually I am wondering why in the getter and not in the constructor of the flash. It will be unperformant to leave at the getter

**Comment by DominicWatson** [comment]
Thinking on this more, if an application will dynamically turn on/off session management per request - it could just use the Cache storage instead of session storage...

You already have logic here for checking session management when initializing this so I think I should just close this PR unless you think otherwise?

**Comment by lmajano** [comment]
I agree @DominicWatson , I am not sure if we need this.

**Comment by DominicWatson** [comment]
Closing, thanks for pointing out the CacheFlash :man_facepalming:

**Pull request closed without merging**
