### PR TITLE
COLDBOX-487 fix for null Errors in populateFromJson

### PR DESCRIPTION
**Pull request by wpdebruin**
COLDBOX-487 fix for null Errors in populateFromJson

### CODE REVIEW

**Comment by evagoras** [comment]
Using this I still get some errors.

Here's my JSON package:
```{"enteredByID":null,"orgName":null}```
The one is an INT and the other is a VARCHAR in the db.

My controller does this:
```var requestContent = toString( getHTTPRequestData().content );
var jsonContent = deserializeJson( requestContent );
var bo = entityService.populateFromJSON( target=bean, JSONString=requestContent );```

My Bean:
```...
property name="enteredByID" column="intEnteredByID" ormtype="integer";
property name="orgName" column="strOrgName" ormtype="string";
...```

And I get this error:
```General application error: Error populating bean approot.modules.v1.models.beans.address with argument orgName of type class java.lang.String.",
    "Detail: <br>Element orgName is undefined in a CFML structure referenced as part of an expression.<br>[{RAW_TRACE={\tat cfBeanPopulator2ecfc1436070246$funcPOPULATEFROMSTRUCT.runFunction(D:\Git\api-abcam-com\approot\coldbox\system\core\dynamic\BeanPopulator.cfc:269)}",
    "LINE={269}",
    "COLUMN={0}",
    "TEMPLATE={D:\Git\api-abcam-com\approot\coldbox\system\core\dynamic\BeanPopulator.cfc}",
    "ID={??}",
    "TYPE={CFML}}",
    " {RAW_TRACE={\tat cfBeanPopulator2ecfc1436070246$funcPOPULATEFROMJSON.runFunction(D:\Git\api-abcam-com\approot\coldbox\system\core\dynamic\BeanPopulator.cfc:45)}",
    "LINE={45}",
    "COLUMN={0}",
    "TEMPLATE={D:\Git\api-abcam-com\approot\coldbox\system\core\dynamic\BeanPopulator.cfc}",
    "ID={CF_UDFMETHOD}",
    "TYPE={CFML}}",
    " {RAW_TRACE={\tat cfBaseORMService2ecfc1254387605$funcPOPULATEFROMJSON.runFunction(D:\Git\api-abcam-com\approot\modules\cborm\models\BaseORMService.cfc:416)}",
    "LINE={416}",
    "COLUMN={0}",
    "TEMPLATE={D:\Git\api-abcam-com\approot\modules\cborm\models\BaseORMService.cfc}",
    "ID={CF_TEMPLATEPROXY}",
    "TYPE={CFML}}",
...```

**Comment by lmajano** [comment]
Can you please update the tests for this as well.

**Comment by wpdebruin** [comment]
Louis, Sorry, I can't update the tests, since I really don't know how to test for Null values in  some mock object. Have to get more experienced with Testbox for this :-(. Actually, I don't even need this patch, I just was trying to be nice to others,..
       myJson='{"Id":8,"Name":"SITE4U_HOSTING","Description":`null}';
myObj=orm.populateFromJSON(target=orm.get("ServiceLevel",8),JSONstring=myJson);
        orm.save(myObj,true);

This is what I tested on a simple orm object with EntityService.

**Comment by evagoras** [comment]
Further tests show that this works 100% fir db VARCHARs.

For INTs, this works:
```
{"enteredByID":null}`
...

This doesn't:
```
{"enteredByID":""}`
```

I get this error:
```at cfBaseORMService2ecfc1254387605$func$TRANSACTIONED.runFunction(D:\Git\api\approot\modules\cborm\models\BaseORMService.cfc:1479)
Message: The value '' cannot be converted to a number.
```

**Comment by bdw429s** [comment]
@lmajano Status on this?  Can you merge this without tests, or do we need to find someone who can help create tests for this fix?

**Pull request merged**
