### PR TITLE
COLDBOX-744 Use a simple array for 'event pool' to avoid locking issu…

### PR DESCRIPTION
**Pull request by DominicWatson**
…es with Syncrhonized maps. This DOES lead to a slightly slower performance when wanting to GET specific interceptos from the map; HOWEVER, this is not a common operation (the most common is just to get the entire pool and loop over it, which carries on working fine with an array).

### CODE REVIEW

**Comment by lmajano** [comment]
Thanks reviewing.

**Comment by lmajano** [comment]
@DominicWatson I have removed the syncrhonized piece from the original source.  I prefer to stick with a hash map as lookups are way faster than iterating and finding states in an array.  I don't see much point on syncronized the map since mostly we do reads, so I have committed it, try it out, and if it satisfies the ticket, we can go with that.

**Comment by lmajano** [comment]
https://github.com/ColdBox/coldbox-platform/commit/d7a8f445d807edd7c32ac9ed8f7f53cdd8f9b3c2

**Comment by DominicWatson** [comment]
Sure thing, good to close from me +1

**Pull request closed without merging**
