### PR TITLE
Fixed typo in ModuleService.cfc

### PR DESCRIPTION
**Pull request by stephen-condon**
Found a typo in the log message

### CODE REVIEW

**Comment by bdw429s** [comment]
@jbampton You sent me an invite to a Github org this morning, but I'm afraid I don't know you or the @gatsbyg org you invited me to.  Are you a bot?

**Comment by jbampton** [comment]
@bdw429s we know each other from Codewars.  You once fixed my CFML translation Complete the Pattern.

**Comment by bdw429s** [comment]
@jbampton Ahh, good to know. :+1:   Did you intend to invite me to your Github org?

**Comment by jbampton** [comment]
@bdw429s  yes I did want to invite you :)  Brand new team.  All private members so far.

**Comment by jbampton** [comment]
Hey @bdw429s I just followed you on Codewars number 2 in the list -> https://www.codewars.com/users/bdw429s/followers

**Pull request merged**
