### PR TITLE
Removed Java file io from FileUtils.cfc

### PR DESCRIPTION
**Pull request by skeltonm**
Allows ColdFusion mappings to be used when referencing file locations.  For example, if you have a CF mapping for Amazon S3 where you are storing files, Java file io does not use that mapping and thus it will not work.

### CODE REVIEW

**Comment by elpete** [comment]
Looks like the line endings are all messed up on this file as well. Can it be ran through something like `mac2unix`?

**Comment by lmajano** [comment]
@skeltonm Can you update the file endings please, we can't review it as it is

**Comment by skeltonm** [comment]
Luis,
It appears that the existing line endings are the old Mac style line endings.  Regardless of what line endings I use (Mac, Unix, Windows) the entire file still shows changes.

**Comment by lmajano** [comment]
No worries I see the Changes now

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com<http://www.ortussolutions.com>
P/F: 1-888-557-8057
________________________________

**Comment by bdw429s** [comment]
Sws aWww s  Issssj sshmkkg


Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------

**Comment by skeltonm** [comment]
Luis,

What is the status of this pull request?  Are you planning on merging it or does it need changes?

**Comment by lmajano** [comment]
It is good, sorry, been swamped. Will be merging this week.

**Comment by lmajano** [comment]
@skeltonm I might have to revert this.  After adding this, all tests fail which require it.

**Comment by bdw429s** [comment]
Probably because the code used spaces instead of tabs! :laughing:

**Comment by skeltonm** [comment]
@bdw429s Actually no, I did use tabs!

**Comment by bdw429s** [comment]
Lol, just messing with ya' :)

**Comment by lmajano** [comment]
LOL!!!
Fixed. It was actually good. FileUtils is very legacy now.  Used mostly from the cf6 days.  I have targeted to be removed in 5.0.0  NOthing was even using it.  The major functionality in use was the ability to send files, which I have refactored into the request context. Seems logically for the request context to deliver files instead of a utility.

**Comment by lmajano** [comment]
https://ortussolutions.atlassian.net/browse/COLDBOX-606

**Comment by skeltonm** [comment]
@lmajano Awesome!  Are you planning on refactoring FileUtils out of ContentBox?

**Pull request merged**
