### PR TITLE
Coldbox 536

### PR DESCRIPTION
**Pull request by bdw429s**
Remove whitespace coming from the interceptor service by converting tags to script

### CODE REVIEW

**Comment by bdw429s** [comment]
https://ortussolutions.atlassian.net/browse/COLDBOX-536

**Comment by lmajano** [comment]
How would this work if the function states it has no output?

**Comment by bdw429s** [comment]
@lmajano I don't understand your question. This is the exact same function, just in script.  Look in the function comment. Output is set to true.

**Comment by lmajano** [comment]
Had to close it as I could not merge it.  Also, I did see now the output. I was missing that.

**Comment by bdw429s** [comment]
Doing a manual merge, I assume?

**Comment by bdw429s** [comment]
@lmajano Are you going to add these changes??

**Comment by lmajano** [comment]
done

**Pull request closed without merging**
