### PR TITLE
Change getSetting default arg to position #2

### PR DESCRIPTION
**Pull request by jclausen**
This will allow for the following syntax:  `getSetting( "foo", "bar" )`

This makes the syntax more intuitive to use and also matches the `getValue` method signature

### CODE REVIEW

**Comment by lmajano** [comment]
@jclausen I think we can break compat and just switch them, have `defaultValue` first and then have the `fwSetting` last.

**Comment by jclausen** [comment]
I’m OK with that.  I will update the PR with the method signature revision

**Comment by lmajano** [comment]
All tests are failing @jclausen

**Comment by jclausen** [comment]
I’ll dig in to it when I get back, but it looks like it’s Adobe-specific and on the Renderer tests: https://travis-ci.org/github/ColdBox/coldbox-platform/jobs/669307937?utm_medium=notification&utm_source=github_status

**Comment by lmajano** [comment]
merged manually now

**Pull request closed without merging**
