### PR TITLE
Add tests for system settings helpers

### PR DESCRIPTION
**Pull request by elpete**

### CODE REVIEW

**Comment by elpete** [comment]
Tests for [this pull request](https://github.com/ColdBox/coldbox-platform/pull/305).

**Comment by elpete** [comment]
@lmajano The tests that are failing on Travis are passing locally.  Build failure?

**Comment by lmajano** [comment]
@elpete tests are failing

**Comment by elpete** [comment]
@lmajano right. Did you see my previous comment? They pass locally so I'm wondering if it is a failure specific to the build. Either way, I could use some help figuring it out.

**Comment by lmajano** [comment]
Hmm, seems there are conflicts now @elpete

**Comment by elpete** [comment]
@lmajano Conflicts resolved

**Pull request merged**
