### PR TITLE
Improve FULL NULL support in ColdBox

### PR DESCRIPTION
**Pull request by michaelborn**
1. Enables null support in GitHub Actions testing
2. Add console log showing whether test suite has full null enabled
3. Fixes many existing issues with coldbox when full null is enabled

### CODE REVIEW

**Comment by lmajano** [comment]
@michaelborn can you help with the conflicts please!@

**Comment by lmajano** [comment]
Sorry @michaelborn I need more help with conflict resolution

**Comment by michaelborn** [comment]
> Sorry @michaelborn I need more help with conflict resolution

I fixed the merge conflict. FWIW, ColdBox clearly didn't work on FULL NULL-enabled engines in the past (and _no one complained_), is it worth the effort to make it compatible now?

**Comment by lmajano** [comment]
Thanks @michaelborn Full null, is weird, we have tried our best, but moving forward, we just need to patch as holes come.

**Pull request closed without merging**
